### ISSUE TITLE
p-value with value 0

### ISSUE THREAD

**Issue by joncchen** [Alcampopiano/hypothesize#12]
Increasing precision doesn't return the exact number.

**Comment by Alcampopiano** [comment]
Hello @joncchen,

Could you please elaborate on the details? For example:

- which function(s) are you referring to?
- which parameters did you you use
- what was the expected output and the actual output

Robust methods operate differently than their traditional analogues in certain respects. Please provide sufficient details and I'd be happy to have a look.
