### ISSUE TITLE
increasing support level to Python 3.11

### ISSUE THREAD

**Issue by cmillion** [Alcampopiano/hypothesize#15]
I saw the talk on `hypothesize` at PyCon, am very interested in using this package, and have started incorporating it into some tooling. The `scipy` version is currently pinned to 1.7.3, which only supports up to Python 3.10. I was wondering if you think there are any barriers to actually bumping that up to a more recent version of `scipy`, or whether you have plans to update for support of 3.11, or if you'd be open to a PR to make that happen. Thanks!

**Comment by Alcampopiano** [comment]
Hi Chase,

Very kind of you to say. I would love to hear more about how you use robust statistics.

I would certainly except a PR for this bump. I don't see any blockers here!
