### ISSUE TITLE
Consistency with WRS2

### ISSUE THREAD

**Issue by chris-park** [Alcampopiano/hypothesize#17]
Hi,

Is this package in sync with [`WRS2 v1.1-5`](https://github.com/cran/WRS2/commit/1443605908ff1327466a196f862958b291bf6e90)?

Thanks

Chris

**Comment by Alcampopiano** [comment]
Hi @chris-park This package includes a subset of functions from WRS (the file found on Wilcox's faculty site). It is not directly based on WRS2 from CRAN.

The function names are consistent with WRS but the API is new.

I hope this helps!
