### ISSUE TITLE
Provide documentation and dependencies for running tests

### ISSUE THREAD

**Issue by arbennett** [Alcampopiano/hypothesize#8]
The contributing documentation describes how tests are structured and tools used, but doesn't actually say how to run the tests. I think adding a sentence or two describing how to run the tests would be useful. Perhaps something like:

> Following installation, to run the test suite first navigate to the `tests` directory then use the `pytest` command.

Additionally, in the `setup.py` it would be useful to add `tests_require=['pytest']` for completeness.

**Comment by Alcampopiano** [comment]
Hello @arbennett,

Thank you for this suggestion. I have added the following sentence as suggested:

> To run the test suite, first navigate to the "tests" directory then use the `pytest` command from your terminal.

I will close this issue but feel free to reopen if I have not fully addressed the issue.
